### ISSUE TITLE
Raw String Question

### ISSUE THREAD

**Issue by MomImProgrammer** [MomImProgrammer/Learning_Python#2]
I played with regex and the following expressions would give the same results and find phone num:

```
phoneNumRegex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')
phoneNumRegex = re.compile('\d\d\d-\d\d\d-\d\d\d\d')
phoneNumRegex = re.compile('\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d')
```

Could you please clarify why is it? I could understand how escaping characters work

When I use phoneNumRegex = re.compile(r'\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d') then it looks for '\d\d\d-\d\d\d-\d\d\d\d' in a text. 
<img width="562" alt="Screenshot 2019-08-04 at 19 21 49" src="https://user-images.githubusercontent.com/51487834/62427620-810b0c00-b6ed-11e9-85c3-29bb71ab6562.png">

**Comment by sphynx** [comment]
Normally, in string literals (i.e. strings in single or double quotes: e.g. 'abc' or "abc") backslash symbol `\` plays a special role. It can help to express symbols like new line (`\n`) or tab (`\t`) or some other "special characters". 

A side effect of this is the fact that if you want to use the backslash symbol literally, you have to prepend it with another backslash (`\\`) to mean that you actually want the backslash itself and not its "special ability" to prepend other characters. So, for example `\n` means a single "new line" character while `\\n` means two characters: backslash followed by `n`.

If you don't want this functionality and just want backslash symbol to always mean itself, then you can use so-called "raw string literals" signified by `r` in front of the literal: `r"hello"` or `r"\n"`.
`r"\n"` would denote two characters string: backslash followed by `n`. Note that you do not need to prepend the backslash with another backslash here. Those raw strings are convenient for example when one uses strings to specify regular expressions, because in regular expressions backslashes occur quite often and have their own meaning. So, in order not to have "double backslashes" everywhere people usually use raw string literals.

I hope this explains why `r"\d"` and `"\\d"` have the same effect. 

Now, to the next question: why `"\d"` and `"\\d"` have the same effect. This is just because `\d` has no special meaning (i.e. there is no character which is encoded as `\d`, even though there is a character encoded as `\n` -- newline character). So `\d` is always parsed as two characters: a backslash followed by `d`. 
However, in general you don't want to rely on this (because it's sometimes hard to keep in mind which symbols have special meaning or not). So, in general it's preferable to use raw literal when expressing regexps, just to be on the safe side.

Please see this StackOverflow answer for a slightly terser explanation:
[SO](
https://stackoverflow.com/questions/2081640/what-exactly-do-u-and-r-string-flags-do-and-what-are-raw-string-literals)

This `python` session shows the difference between `\n` and `\d`. While `\d` is the same in all three incarnations, `\n` is different:

```
>>> '\d'
'\\d'
>>> '\\d'
'\\d'
>>> r'\d'
'\\d'


>>> '\n'
'\n'
>>> '\\n'
'\\n'
>>> r'\n'
'\\n'
```
